
package vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;

/**
 *
 * @author Liliana
 */
public class FormularioMenu extends javax.swing.JFrame {

   public static JDesktopPane jDesktopPane_menu;
    
    public FormularioMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Lonas JETH");
        
        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/inicio.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_nuevo_usuario = new javax.swing.JMenuItem();
        jMenuItem_agregar_usuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_administrar_productos = new javax.swing.JMenuItem();
        jMenuItem_agregar_producto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_administrar_categorias = new javax.swing.JMenuItem();
        jMenuItem_agregar_categoria = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido!");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario2.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 36));

        jMenuItem_nuevo_usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem_nuevo_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuracion1.png"))); // NOI18N
        jMenuItem_nuevo_usuario.setText("Administrar Usuarios");
        jMenuItem_nuevo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_nuevo_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_nuevo_usuario);

        jMenuItem_agregar_usuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem_agregar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarusuario.png"))); // NOI18N
        jMenuItem_agregar_usuario.setText("Agregar Usuario");
        jMenuItem_agregar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_agregar_usuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_agregar_usuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto1.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 36));

        jMenuItem_administrar_productos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem_administrar_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuracion1.png"))); // NOI18N
        jMenuItem_administrar_productos.setText("Administrar Productos");
        jMenuItem_administrar_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_administrar_productosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_administrar_productos);

        jMenuItem_agregar_producto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem_agregar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarproducto.png"))); // NOI18N
        jMenuItem_agregar_producto.setText("Agregar Producto");
        jMenuItem_agregar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_agregar_productoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_agregar_producto);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias1.png"))); // NOI18N
        jMenu3.setText("Categoría");
        jMenu3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 36));

        jMenuItem_administrar_categorias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem_administrar_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuracion1.png"))); // NOI18N
        jMenuItem_administrar_categorias.setText("Administrar Categorías");
        jMenuItem_administrar_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_administrar_categoriasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_administrar_categorias);

        jMenuItem_agregar_categoria.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem_agregar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregarcategoria.png"))); // NOI18N
        jMenuItem_agregar_categoria.setText("Agregar Categoría");
        jMenuItem_agregar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_agregar_categoriaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_agregar_categoria);

        jMenuBar1.add(jMenu3);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsesion.png"))); // NOI18N
        jMenu8.setText("Cerrar Sesión");
        jMenu8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jMenu8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 36));

        jMenuItem_cerrar_sesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsesion.png"))); // NOI18N
        jMenuItem_cerrar_sesion.setText("See You!");
        jMenu8.add(jMenuItem_cerrar_sesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_agregar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_agregar_categoriaActionPerformed
        // TODO add your handling code here:
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem_agregar_categoriaActionPerformed

    private void jMenuItem_administrar_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_administrar_categoriasActionPerformed
        // TODO add your handling code here:
        InterAdminCat interAdminCat = new InterAdminCat();
        jDesktopPane_menu.add(interAdminCat);
        interAdminCat.setVisible(true);
    }//GEN-LAST:event_jMenuItem_administrar_categoriasActionPerformed

    private void jMenuItem_agregar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_agregar_productoActionPerformed
        // TODO add your handling code here:
        InterProducto interProducto = new InterProducto();
        jDesktopPane_menu.add(interProducto);
        interProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem_agregar_productoActionPerformed

    private void jMenuItem_administrar_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_administrar_productosActionPerformed
        // TODO add your handling code here:
        InterAdminProduct interAdminProduct = new InterAdminProduct();
        jDesktopPane_menu.add(interAdminProduct);
        interAdminProduct.setVisible(true);
    }//GEN-LAST:event_jMenuItem_administrar_productosActionPerformed

    private void jMenuItem_agregar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_agregar_usuarioActionPerformed
        // TODO add your handling code here:
        InterUsuario interUsuario = new InterUsuario();
        jDesktopPane_menu.add(interUsuario);
        interUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem_agregar_usuarioActionPerformed

    private void jMenuItem_nuevo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_nuevo_usuarioActionPerformed
        // TODO add your handling code here:
        InterAdminUsuario interAdminUsuario = new InterAdminUsuario();
        jDesktopPane_menu.add(interAdminUsuario);
        interAdminUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem_nuevo_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_administrar_categorias;
    private javax.swing.JMenuItem jMenuItem_administrar_productos;
    private javax.swing.JMenuItem jMenuItem_agregar_categoria;
    private javax.swing.JMenuItem jMenuItem_agregar_producto;
    private javax.swing.JMenuItem jMenuItem_agregar_usuario;
    private javax.swing.JMenuItem jMenuItem_cerrar_sesion;
    private javax.swing.JMenuItem jMenuItem_nuevo_usuario;
    // End of variables declaration//GEN-END:variables
}
